org.gradle.jvmargs=-Xmx3G

mod_version = 1.4.1
maven_group = net.pitan76
archives_base_name = AdvancedReborn-26.2

minecraft_version=26.2
loader_version=0.19.3

# Fabric API
fabric_api_version=0.158.0+26.2

cc_version=1.120.2

mcpitanlib_version=-26.2:4.0.7

changelog=Fixed machine GUI not opening, Farming/Logging Machine not working, Cardboard Box variant crash, Centrifugal Extractor item duplication, and Overclocker support for the Enchantment Extractor
